export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'
export const BUSCAR_PRODUCTOS = 'BUSCAR_PRODUCTOS'
export const REINICIAR_PRODUCTOS = 'REINICIAR_PRODUCTOS'
export const FILTROS_PRODUCTO = 'FILTROS_PRODUCTO'